const JobList = [
  {
    //Front-end
    company: "company ABC",
    position: "Junior Front-end",
    experience: "Entry level",
    location: "Makati",
    page: "/JobDescription",
  },
  {
    company: "company 123",
    position: "Junior Front-end",
    experience: "Entry level",
    location: "Cebu",
    page: "/JobDescription",
  },
  {
    company: "company XYZ",
    position: "Junior Front-end",
    experience: "Entry level",
    location: "Davao",
    page: "/JobDescription",
  },
  {
    company: "company ABC",
    position: "Senior Front-end",
    experience: "4+ years",
    location: "Makati",
    page: "/JobDescription",
  },
  {
    company: "company 123",
    position: "Senior Front-end",
    experience: "4+ years",
    location: "Cebu",
    page: "/JobDescription",
  },
  {
    company: "company XYZ",
    position: "Senior Front-end",
    experience: "4+ years",
    location: "Davao",
    page: "/JobDescription",
  },
  {
    //Back-end
    company: "company ABC",
    position: "Junior Back-end",
    experience: "Entry level",
    location: "Makati",
    page: "/JobDescription",
  },
  {
    company: "company 123",
    position: "Junior Back-end",
    experience: "Entry level",
    location: "Cebu",
    page: "/JobDescription",
  },
  {
    company: "company XYZ",
    position: "Junior Back-end",
    experience: "Entry level",
    location: "Davao",
    page: "/JobDescription",
  },
  {
    company: "company ABC",
    position: "Senior Back-end",
    experience: "4+ years",
    location: "Makati",
    page: "/JobDescription",
  },
  {
    company: "company 123",
    position: "Senior Back-end",
    experience: "4+ years",
    location: "Cebu",
    page: "/JobDescription",
  },
  {
    company: "company XYZ",
    position: "Senior Back-end",
    experience: "4+ years",
    location: "Davao",
    page: "/JobDescription",
  },
  {
    //QA Tester
    company: "company ABC",
    position: "Junior QA Tester",
    experience: "Entry level",
    location: "Makati",
    page: "/JobDescription",
  },
  {
    company: "company 123",
    position: "Junior QA Tester",
    experience: "Entry level",
    location: "Cebu",
    page: "/JobDescription",
  },
  {
    company: "company XYZ",
    position: "Junior QA Tester",
    experience: "Entry level",
    location: "Davao",
    page: "/JobDescription",
  },
  {
    company: "company ABC",
    position: "Senior QA Tester",
    experience: "4+ years",
    location: "Makati",
    page: "/JobDescription",
  },
  {
    company: "company 123",
    position: "Senior QA Tester",
    experience: "4+ years",
    location: "Cebu",
    page: "/JobDescription",
  },
  {
    company: "company XYZ",
    position: "Senior QA Tester",
    experience: "4+ years",
    location: "Davao",
    page: "/JobDescription",
  },
  {
    // UI/UX Designer
    company: "company ABC",
    position: "Junior UI/UX Designer",
    experience: "Entry level",
    location: "Makati",
    page: "/JobDescription",
  },
  {
    company: "company 123",
    position: "Junior UI/UX Designer",
    experience: "Entry level",
    location: "Cebu",
    page: "/JobDescription",
  },
  {
    company: "company XYZ",
    position: "Junior UI/UX Designer",
    experience: "Entry level",
    location: "Davao",
    page: "/JobDescription",
  },
  {
    company: "company ABC",
    position: "Senior UI/UX Designer",
    experience: "4+ years",
    location: "Makati",
    page: "/JobDescription",
  },
  {
    company: "company 123",
    position: "Senior UI/UX Designer",
    experience: "4+ years",
    location: "Cebu",
    page: "/JobDescription",
  },
  {
    company: "company XYZ",
    position: "Senior UI/UX Designer",
    experience: "4+ years",
    location: "Davao",
    page: "/JobDescription",
  },
  {
    //Database
    company: "company ABC",
    position: "Database Manager",
    experience: "4+ years",
    location: "Makati",
    page: "/JobDescription",
  },
  {
    company: "company 123",
    position: "Database Manager",
    experience: "4+ years",
    location: "Cebu",
    page: "/JobDescription",
  },
  {
    company: "company XYZ",
    position: "Database Manager",
    experience: "4+ years",
    location: "Davao",
    page: "/JobDescription",
  },
];
export default JobList;
